Support Ruby 3
aptible/fridge pull request #14
Opened 2022-11-06 23:56 UTC by almathew

2022-11-07 02:03 UTC, fancyremarker requested changes

2022-11-07 02:03 UTC, fancyremarker commented on Gemfile
> +gem 'activesupport'
Instead, we should just remove these dependencies if we no longer care about a version. (They're being pulled in implicitly by Rails.)

2022-11-07 20:55 UTC, fancyremarker commented
@almathew : (same comment as aptible/aptible_api_shared#47) as discussed in Slack, I'm leaving this open until we can confirm deploy-api tests pass on the updated gem; perhaps open a deploy-api PR with gems pinned to branches and assign me to review it?

2022-11-09 16:03 UTC, almathew commented
I shared this in the aptible_api_shared repo, but downstream tests have been updated to use this version of fridge and are passing.

2022-11-30 15:26 UTC, mdelaossa approved these changes
since downstream is passing, approving

2022-11-30 15:53 UTC, almathew commented
I'm merging with @mdelaossa 's approval because all of @fancyremarker 's requested changes were met.

2022-11-30 15:53 UTC, merged